[project]
name = "comicrag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "chroma>=0.2.0",
    "chromadb>=1.3.5",
    "numpy>=2.0.2",
    "pillow>=11.3.0",
    "torch>=2.2.2",
    "transformers>=4.57.3",
]

[tool.uv]
# require support for Intel macOS
required-environments = [
  "sys_platform == 'darwin' and platform_machine == 'x86_64'"
]

